In [1]:
import os
from pathlib import Path
from sqlalchemy import create_engine, text, bindparam
import pandas as pd
import requests
import numpy as np

In [2]:
BASE_DIR = os.path.dirname(Path(os.path.abspath('')))
DATABASE_DIR = os.path.join(BASE_DIR, "db")
DATABASE_FILE_PATH = os.path.join(DATABASE_DIR, "game-data.sqlite")
engine = create_engine(f"sqlite:///{DATABASE_FILE_PATH}")
NHL_API_BASE_URL = "https://api-web.nhle.com/v1"

In [3]:
pd.set_option('display.max_columns', None)

## Data Import

In [4]:
unblocked_query = """
WITH GoalieIdJoin AS (
SELECT
shots.gameId,
shots.season,
shots.TeamId,
shots.TeamName,
shots.isHomeTeam,
shots.Prev25FenwickForPerHour,
shots.Prev25FenwickAgainstPerHour,
pp.Prev25ShotsFor5v4PerHour,
pp.Prev25ShotsAgainst4v5PerHour,
spct.Prev25ShootingPercentage,
playerId as GoalieId
FROM UnblockedShotGenSupLast25 AS shots 
LEFT JOIN goalie_saves as gs ON shots.gameId = gs.gameId AND ((shots.isHomeTeam = 1 AND gs.homeRoad = 'H') OR (shots.isHomeTeam = 0 AND gs.homeRoad = 'R')) and gs.gamesStarted = 1 
LEFT JOIN ShotGenSup5v4Last25 as pp ON pp.id = shots.gameId AND pp.teamId = shots.TeamId
LEFT JOIN TeamScoringPercentage as spct ON spct.id = shots.gameId AND spct.teamId = shots.TeamId
)
SELECT GoalieIdJoin.*,
gsave.diluted_save_pct,
games.homeScore > games.visitingScore AS HomeTeamWin
FROM GoalieIdJoin
LEFT JOIN GoalieSavePct as gsave ON gsave.goalieId = GoalieIdJoin.GoalieId
LEFT JOIN games ON games.id = GoalieIdJoin.gameId
"""
UnblockedShotGenSup = pd.read_sql_query(unblocked_query, engine)

In [5]:
df = UnblockedShotGenSup

In [6]:
df

,gameId,season,TeamId,TeamName,isHomeTeam,Prev25FenwickForPerHour,Prev25FenwickAgainstPerHour,Prev25ShotsFor5v4PerHour,Prev25ShotsAgainst4v5PerHour,Prev25ShootingPercentage,GoalieId,diluted_save_pct,HomeTeamWin
0,2010020007,20102011,1,New Jersey Devils,1,NaN,NaN,NaN,NaN,NaN,8455710.0,0.913166,0
1,2010020017,20102011,1,New Jersey Devils,0,35.731046,37.251655,40.449438,60.000000,0.080000,8455710.0,0.913166,1
2,2010020027,20102011,1,New Jersey Devils,1,39.097642,41.677380,79.120879,56.814921,0.061224,8455710.0,0.913166,0
3,2010020036,20102011,1,New Jersey Devils,0,37.648014,42.139441,87.022901,63.258786,0.055556,8455710.0,0.913166,0
4,2010020048,20102011,1,New Jersey Devils,1,40.259124,40.970034,91.099476,69.973190,0.040000,8455710.0,0.913166,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
43665,2025020060,20252026,68,Utah Mammoth,1,39.725217,33.977351,92.988930,87.804878,0.053571,8478872.0,0.913827,1
43666,2025020075,20252026,68,Utah Mammoth,1,40.304810,35.590220,101.730104,87.961859,0.064935,8478872.0,0.913827,1
43667,2025020092,20252026,68,None,1,41.427192,32.957497,110.273327,87.896104,0.098039,8477970.0,0.916088,0
43668,2025020107,20252026,68,None,1,41.427192,32.957497,110.273327,87.896104,0.098039,NaN,NaN,0
43669,2025020117,20252026,68,None,0,41.427192,32.957497,110.273327,87.896104,0.098039,NaN,NaN,0

In [7]:
df.sort_values(by="gameId", ascending=False)

,gameId,season,TeamId,TeamName,isHomeTeam,Prev25FenwickForPerHour,Prev25FenwickAgainstPerHour,Prev25ShotsFor5v4PerHour,Prev25ShotsAgainst4v5PerHour,Prev25ShootingPercentage,GoalieId,diluted_save_pct,HomeTeamWin
43569,2025020126,20252026,20,None,0,41.569414,40.664710,86.205102,111.455108,0.070588,NaN,NaN,0
43646,2025020126,20252026,52,None,1,26.716608,38.362516,131.220285,111.428571,0.181818,NaN,NaN,0
43529,2025020125,20252026,15,None,0,44.999972,39.981035,109.874327,99.428571,0.088710,NaN,NaN,0
43630,2025020125,20252026,29,None,1,42.470177,51.866559,86.971527,126.266563,0.089888,NaN,NaN,0
43425,2025020124,20252026,1,None,1,46.406479,39.886922,112.500000,76.638655,0.100000,NaN,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2556,2010020003,20102011,30,Minnesota Wild,1,NaN,NaN,NaN,NaN,NaN,8473404.0,0.920782,0
344,2010020002,20102011,5,Pittsburgh Penguins,1,NaN,NaN,NaN,NaN,NaN,8470594.0,0.921912,0
251,2010020002,20102011,4,Philadelphia Flyers,0,NaN,NaN,NaN,NaN,NaN,8475683.0,0.924056,0
800,2010020001,20102011,10,Toronto Maple Leafs,1,NaN,NaN,NaN,NaN,NaN,8462044.0,0.919566,1
629,2010020001,20102011,8,Montréal Canadiens,0,NaN,NaN,NaN,NaN,NaN,8471679.0,0.927053,1

## Data Processing

In [8]:
df_home = df[df["isHomeTeam"] == 1].rename(columns={
    "TeamName": "HomeTeamName",
    "TeamId": "HomeTeamId",
    "Prev25FenwickForPerHour": "HomePrev25FenwickForPerHour",
    "Prev25FenwickAgainstPerHour": "HomePrev25FenwickAgainstPerHour",
    "Prev25ShotsFor5v4PerHour": "HomePrev25ShotsFor5v4PerHour",
    "Prev25ShotsAgainst4v5PerHour": "HomePrev25ShotsAgainst4v5PerHour",
    "Prev25ShootingPercentage": "HomePrev25ShootingPercentage",
    "GoalieId": "HomeGoalieId",
    "diluted_save_pct": "HomeDilutedSavePct"
}).drop(["isHomeTeam"], axis=1)
df_away = df[df["isHomeTeam"] == 0].rename(columns={
    "TeamName": "AwayTeamName",
    "TeamId": "AwayTeamId",
    "Prev25FenwickForPerHour": "AwayPrev25FenwickForPerHour",
    "Prev25FenwickAgainstPerHour": "AwayPrev25FenwickAgainstPerHour",
    "Prev25ShotsFor5v4PerHour": "AwayPrev25ShotsFor5v4PerHour",
    "Prev25ShotsAgainst4v5PerHour": "AwayPrev25ShotsAgainst4v5PerHour",
    "Prev25ShootingPercentage": "AwayPrev25ShootingPercentage",
    "GoalieId": "AwayGoalieId",
    "diluted_save_pct": "AwayDilutedSavePct"
}).drop(["season", "isHomeTeam", "HomeTeamWin"], axis=1)

In [9]:
df_com = pd.merge(left=df_home, right=df_away, how="left", on="gameId")

In [10]:
df_com.loc[df_com.isnull().any(axis=1)]

,gameId,season,HomeTeamId,HomeTeamName,HomePrev25FenwickForPerHour,HomePrev25FenwickAgainstPerHour,HomePrev25ShotsFor5v4PerHour,HomePrev25ShotsAgainst4v5PerHour,HomePrev25ShootingPercentage,HomeGoalieId,HomeDilutedSavePct,HomeTeamWin,AwayTeamId,AwayTeamName,AwayPrev25FenwickForPerHour,AwayPrev25FenwickAgainstPerHour,AwayPrev25ShotsFor5v4PerHour,AwayPrev25ShotsAgainst4v5PerHour,AwayPrev25ShootingPercentage,AwayGoalieId,AwayDilutedSavePct
0,2010020007,20102011,1,New Jersey Devils,NaN,NaN,NaN,NaN,NaN,8455710.0,0.913166,0,25,Dallas Stars,NaN,NaN,NaN,NaN,NaN,8470140.0,0.923361
41,2010020015,20102011,2,New York Islanders,NaN,NaN,NaN,NaN,NaN,8468481.0,0.906516,0,25,Dallas Stars,36.726480,35.227308,60.000000,40.449438,0.130435,8470140.0,0.923361
172,2010020002,20102011,5,Pittsburgh Penguins,NaN,NaN,NaN,NaN,NaN,8470594.0,0.921912,0,4,Philadelphia Flyers,NaN,NaN,NaN,NaN,NaN,8475683.0,0.924056
217,2010020012,20102011,6,Boston Bruins,NaN,NaN,NaN,NaN,NaN,8471695.0,0.927981,0,27,Phoenix Coyotes,NaN,NaN,NaN,NaN,NaN,8468524.0,0.922107
271,2010020013,20102011,7,Buffalo Sabres,44.570909,37.650589,112.720157,93.413174,0.043478,8468011.0,0.923425,0,3,New York Rangers,NaN,NaN,NaN,NaN,NaN,8468685.0,0.926831
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38753,2025020087,20252026,54,None,44.078153,38.114661,108.531110,97.864078,0.086207,8478499.0,0.914555,0,20,None,41.569414,40.664710,86.205102,111.455108,0.070588,8481692.0,0.918216
38754,2025020097,20252026,54,None,44.078153,38.114661,108.531110,97.864078,0.086207,NaN,NaN,0,12,None,58.980679,31.056967,110.473649,64.864865,0.130435,NaN,NaN
38755,2025020021,20252026,55,Seattle Kraken,NaN,NaN,NaN,NaN,NaN,8478916.0,0.920209,1,24,Anaheim Ducks,NaN,NaN,NaN,NaN,NaN,8480843.0,0.916365
38759,2025020092,20252026,68,None,41.427192,32.957497,110.273327,87.896104,0.098039,8477970.0,0.916088,0,6,None,45.841060,42.063199,106.521739,90.789474,0.103774,8476914.0,0.913187
38760,2025020107,20252026,68,None,41.427192,32.957497,110.273327,87.896104,0.098039,NaN,NaN,0,21,None,49.665125,39.645786,92.817680,84.450402,0.094488,NaN,NaN

In [11]:
df_nn = df_com.loc[df_com["HomePrev25FenwickAgainstPerHour"].notna() & df_com["AwayPrev25FenwickForPerHour"].notna()].copy()
df_nn.dropna(inplace=True)

In [12]:
df_std = df_nn.copy()
cols_to_standardize = ["HomePrev25FenwickForPerHour", "HomePrev25FenwickAgainstPerHour", "HomePrev25ShotsFor5v4PerHour", "HomePrev25ShotsAgainst4v5PerHour", "HomePrev25ShootingPercentage", "HomeDilutedSavePct", "AwayPrev25FenwickForPerHour", "AwayPrev25FenwickAgainstPerHour", "AwayPrev25ShotsFor5v4PerHour", "AwayPrev25ShotsAgainst4v5PerHour", "AwayPrev25ShootingPercentage", "AwayDilutedSavePct"]
df_std[cols_to_standardize] = df_std.groupby('season')[cols_to_standardize].transform(
    lambda x: (x - x.mean()) / x.std()
)

In [13]:
df_std.dtypes

gameId                                int64
season                                int64
HomeTeamId                            int64
HomeTeamName                         object
HomePrev25FenwickForPerHour         float64
HomePrev25FenwickAgainstPerHour     float64
HomePrev25ShotsFor5v4PerHour        float64
HomePrev25ShotsAgainst4v5PerHour    float64
HomePrev25ShootingPercentage        float64
HomeGoalieId                        float64
HomeDilutedSavePct                  float64
HomeTeamWin                           int64
AwayTeamId                            int64
AwayTeamName                         object
AwayPrev25FenwickForPerHour         float64
AwayPrev25FenwickAgainstPerHour     float64
AwayPrev25ShotsFor5v4PerHour        float64
AwayPrev25ShotsAgainst4v5PerHour    float64
AwayPrev25ShootingPercentage        float64
AwayGoalieId                        float64
AwayDilutedSavePct                  float64
dtype: object

In [38]:
df_std.iloc[0]

gameId                                       2010020027
season                                         20102011
HomeTeamId                                            1
HomeTeamName                          New Jersey Devils
HomePrev25FenwickForPerHour                   -0.649706
HomePrev25FenwickAgainstPerHour                0.118334
HomePrev25ShotsFor5v4PerHour                  -1.140181
HomePrev25ShotsAgainst4v5PerHour              -3.099001
HomePrev25ShootingPercentage                  -1.067386
HomeGoalieId                                  8455710.0
HomeDilutedSavePct                            -1.701022
HomeTeamWin                                           0
AwayTeamId                                            5
AwayTeamName                        Pittsburgh Penguins
AwayPrev25FenwickForPerHour                    1.858938
AwayPrev25FenwickAgainstPerHour               -0.359108
AwayPrev25ShotsFor5v4PerHour                  -1.692692
AwayPrev25ShotsAgainst4v5PerHour               -0.75114
AwayPrev25ShootingPercentage                  -2.574698
AwayGoalieId                                  8462161.0
AwayDilutedSavePct                            -0.755639
Name: 1, dtype: object

In [42]:
import pickle

cols = ["HomePrev25FenwickForPerHour",
        "AwayPrev25FenwickForPerHour",
        "HomePrev25FenwickAgainstPerHour",
        "AwayPrev25FenwickAgainstPerHour",
        "HomePrev25ShotsFor5v4PerHour",
        "AwayPrev25ShotsFor5v4PerHour",
        "HomePrev25ShotsAgainst4v5PerHour",
        "AwayPrev25ShotsAgainst4v5PerHour",
        "HomePrev25ShootingPercentage",
        "AwayPrev25ShootingPercentage",
        "HomeDilutedSavePct",
        "AwayDilutedSavePct"]

# Specify the filename of your saved model
filename = '../hockey_pipeline/src/hockey_pipeline/defs/oscar/oscar.pkl'

# Load the model from the file
with open(filename, 'rb') as f:
    loaded_model = pickle.load(f)
    print(df_std[cols].iloc[0].values.reshape(1, -1))
    print(loaded_model.predict(df_std[cols].iloc[0].values.reshape(1, -1)))

[[-0.6497059   1.85893772  0.1183343  -0.35910819 -1.14018086 -1.69269178
  -3.09900119 -0.7511404  -1.06738604 -2.57469785 -1.70102214 -0.75563947]]
[1]

/Users/tristanrussell/Documents/hockeydata/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

## Logistic Regression Model Fitting

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
df_std.dtypes

gameId                                int64
season                                int64
HomeTeamId                            int64
HomeTeamName                         object
HomePrev25FenwickForPerHour         float64
HomePrev25FenwickAgainstPerHour     float64
HomePrev25ShotsFor5v4PerHour        float64
HomePrev25ShotsAgainst4v5PerHour    float64
HomePrev25ShootingPercentage        float64
HomeGoalieId                        float64
HomeDilutedSavePct                  float64
HomeTeamWin                           int64
AwayTeamId                            int64
AwayTeamName                         object
AwayPrev25FenwickForPerHour         float64
AwayPrev25FenwickAgainstPerHour     float64
AwayPrev25ShotsFor5v4PerHour        float64
AwayPrev25ShotsAgainst4v5PerHour    float64
AwayPrev25ShootingPercentage        float64
AwayGoalieId                        float64
AwayDilutedSavePct                  float64
dtype: object

In [42]:
cols = ["HomePrev25FenwickForPerHour",
        "AwayPrev25FenwickForPerHour",
        "HomePrev25FenwickAgainstPerHour", 
        "AwayPrev25FenwickAgainstPerHour",
        "HomePrev25ShotsFor5v4PerHour", 
        "AwayPrev25ShotsFor5v4PerHour",
        "HomePrev25ShotsAgainst4v5PerHour", 
        "AwayPrev25ShotsAgainst4v5PerHour",
        "HomePrev25ShootingPercentage", 
        "AwayPrev25ShootingPercentage",
        "HomeDilutedSavePct", 
        "AwayDilutedSavePct"]
X = df_std[cols].copy()
Y = df_std[["HomeTeamWin"]].copy()

In [43]:
log_reg = LogisticRegression()
log_reg.fit(X, Y.values.ravel())

LogisticRegression()

In [44]:
list(zip(cols, log_reg.coef_[0]))

[('HomePrev25FenwickForPerHour', np.float64(0.09164746441369945)),
 ('AwayPrev25FenwickForPerHour', np.float64(-0.10796864506640294)),
 ('HomePrev25FenwickAgainstPerHour', np.float64(-0.10799787778252273)),
 ('AwayPrev25FenwickAgainstPerHour', np.float64(0.06433838113119308)),
 ('HomePrev25ShotsFor5v4PerHour', np.float64(-0.024317240579072447)),
 ('AwayPrev25ShotsFor5v4PerHour', np.float64(-0.05764681991454236)),
 ('HomePrev25ShotsAgainst4v5PerHour', np.float64(-0.01560760493471113)),
 ('AwayPrev25ShotsAgainst4v5PerHour', np.float64(0.044551229614200445)),
 ('HomePrev25ShootingPercentage', np.float64(-0.016769085178029705)),
 ('AwayPrev25ShootingPercentage', np.float64(-0.07270555156864159)),
 ('HomeDilutedSavePct', np.float64(0.14630670257468534)),
 ('AwayDilutedSavePct', np.float64(-0.160423860805149))]

In [45]:
cols_pip = ["HomePrev25FenwickForPerHour",
        "AwayPrev25FenwickForPerHour",
        "HomePrev25FenwickAgainstPerHour", 
        "AwayPrev25FenwickAgainstPerHour"]
X_Pip = df_std[cols_pip].copy()
log_reg.fit(X_Pip, Y.values.ravel())

LogisticRegression()

In [46]:
list(zip(cols_pip, log_reg.coef_[0]))

[('HomePrev25FenwickForPerHour', np.float64(0.09476284895944306)),
 ('AwayPrev25FenwickForPerHour', np.float64(-0.12425176160901243)),
 ('HomePrev25FenwickAgainstPerHour', np.float64(-0.10743302803199677)),
 ('AwayPrev25FenwickAgainstPerHour', np.float64(0.08086551284958746))]

## Logistic Regression Grid Search

In [47]:
from sklearn.model_selection import cross_val_score, GridSearchCV

In [48]:
log_reg = LogisticRegression()
scores = cross_val_score(log_reg, X, Y.values.ravel(), cv=5, scoring="neg_brier_score")
print(scores)

[-0.24232449 -0.25129833 -0.24103365 -0.24606143 -0.24752208]

In [49]:
gs = GridSearchCV(log_reg, {
    'C': [0.01, 0.1, 1, 10, 100],
    'fit_intercept': [True, False],
    'solver': ["liblinear", "newton-cholesky", "newton-cg", "saga"]
}, cv=5)

In [50]:
gs.fit(X, Y.values.ravel())

GridSearchCV(cv=5, estimator=LogisticRegression(),
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'fit_intercept': [True, False],
                         'solver': ['liblinear', 'newton-cholesky', 'newton-cg',
                                    'saga']})

In [51]:
gs.best_score_

np.float64(0.5462771970919461)

In [52]:
gs.best_estimator_.coef_

array([[ 0.0910069 , -0.10694732, -0.10652245,  0.06400875, -0.02341297,
        -0.05735022, -0.01624346,  0.04447625, -0.01673595, -0.07160007,
         0.144533  , -0.15853346]])

In [53]:
df_com

,gameId,season,HomeTeamId,HomeTeamName,HomePrev25FenwickForPerHour,HomePrev25FenwickAgainstPerHour,HomePrev25ShotsFor5v4PerHour,HomePrev25ShotsAgainst4v5PerHour,HomePrev25ShootingPercentage,HomeGoalieId,HomeDilutedSavePct,HomeTeamWin,AwayTeamId,AwayTeamName,AwayPrev25FenwickForPerHour,AwayPrev25FenwickAgainstPerHour,AwayPrev25ShotsFor5v4PerHour,AwayPrev25ShotsAgainst4v5PerHour,AwayPrev25ShootingPercentage,AwayGoalieId,AwayDilutedSavePct
0,2010020007,20102011,1,New Jersey Devils,NaN,NaN,NaN,NaN,NaN,8455710.0,0.913166,0,25,Dallas Stars,NaN,NaN,NaN,NaN,NaN,8470140.0,0.923361
1,2010020027,20102011,1,New Jersey Devils,39.097642,41.677380,79.120879,56.814921,0.061224,8455710.0,0.913166,0,5,Pittsburgh Penguins,48.223979,40.013922,71.523179,84.297521,0.038462,8462161.0,0.916907
2,2010020048,20102011,1,New Jersey Devils,40.259124,40.970034,91.099476,69.973190,0.040000,8455710.0,0.913166,0,21,Colorado Avalanche,42.874015,42.267633,62.983425,110.297872,0.082353,8467950.0,0.919413
3,2010020056,20102011,1,New Jersey Devils,41.302035,40.910259,101.160660,67.648553,0.039062,8455710.0,0.913166,0,6,Boston Bruins,52.916474,45.152332,105.017503,108.724832,0.066667,8460703.0,0.927824
4,2010020100,20102011,1,New Jersey Devils,39.890359,41.584814,94.778412,74.913295,0.052632,8460704.0,0.917676,0,7,Buffalo Sabres,44.323222,38.074503,98.392283,101.694915,0.071770,8468011.0,0.923425
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38756,2025020037,20252026,55,Seattle Kraken,51.018365,55.015194,45.000000,90.000000,0.100000,8478916.0,0.920209,1,54,Vegas Golden Knights,45.633869,32.853356,80.000000,97.297297,0.083333,8478499.0,0.914555
38757,2025020060,20252026,68,Utah Mammoth,39.725217,33.977351,92.988930,87.804878,0.053571,8478872.0,0.913827,1,20,Calgary Flames,41.683309,40.304264,85.659164,109.006211,0.084507,8482445.0,0.912521
38758,2025020075,20252026,68,Utah Mammoth,40.304810,35.590220,101.730104,87.961859,0.064935,8478872.0,0.913827,1,28,San Jose Sharks,28.194313,63.029219,77.450199,96.601073,0.127660,8482137.0,0.916193
38759,2025020092,20252026,68,None,41.427192,32.957497,110.273327,87.896104,0.098039,8477970.0,0.916088,0,6,None,45.841060,42.063199,106.521739,90.789474,0.103774,8476914.0,0.913187
38760,2025020107,20252026,68,None,41.427192,32.957497,110.273327,87.896104,0.098039,NaN,NaN,0,21,None,49.665125,39.645786,92.817680,84.450402,0.094488,NaN,NaN

In [66]:
with engine.connect() as conn:
    res = conn.execute(text("""
    SELECT triCode FROM teams WHERE id = 52
    """))
    code = res.all()[0][0]

In [67]:
roster = requests.get(f"{NHL_API_BASE_URL}/roster/{code}/20252026")

In [72]:
goalie_ids = [goalie["id"] for goalie in roster.json()["goalies"]]